DictVectorizer = > BOW 인코딩 벡터

In [1]:
from sklearn.feature_extraction import DictVectorizer

In [4]:
v = DictVectorizer(sparse=False)
D=[{'A':1,'B':2},{'B':3,'C':1}] #중괄호는 하나의 문장, 하나의 문장의 키값은 단어
# 3종 단어롤 이루어진다. 벡터의 차원의 3. 각 단어는 인덱스를 나타내고 인덱스의 값은 그 단어의 빈도수
#각 단어의 빈도수를 미리 알아야 사용가능
X = v.fit_transform(D)
print(X)
print(type(X))

[[1. 2. 0.]
 [0. 3. 1.]]
<class 'numpy.ndarray'>


In [5]:
v.feature_names_

['A', 'B', 'C']

In [6]:
D2 = {'A':5, 'B':1,"D":100}

In [7]:
v.transform(D2)

array([[5., 1., 0.]])

CounterVectorizer => BOW 인코딩 벡터 문서의 집합-> 단어토큰생성-> 각단어의 수

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
    'The last document?',
]

In [12]:
v1=CountVectorizer()
#문장 토큰화가 완료되어야 한다.
v1.fit(corpus)
v1.vocabulary_

{'this': 9,
 'is': 3,
 'the': 7,
 'first': 2,
 'document': 1,
 'second': 6,
 'and': 0,
 'third': 8,
 'one': 5,
 'last': 4}

In [14]:
v1.transform(['This is the first document. This is the man']).toarray()

array([[0, 1, 1, 2, 0, 0, 0, 2, 0, 2]], dtype=int64)